CREATE DATABASE  IF NOT EXISTS `curso`;
USE `curso`;
DROP TABLE IF EXISTS `menu`;
CREATE TABLE `menu` (`id` int(11) NOT NULL AUTO_INCREMENT,`pagina` varchar(45) NOT NULL,`link` varchar(45) NOT NULL,`principal` char(1) NOT NULL,`conteudo` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;
LOCK TABLES `menu` WRITE;
INSERT INTO `menu` VALUES (1,'home','Home','S','<h1>Site simples em PHP</h1>\n<p>Este site faz parte do primeiro Projeto a ser entregue, desenvolvido com o Twitter Bootstrap.</p>');
INSERT INTO `menu` VALUES (2,'empresa','Empresa','N','<h1>Empresa</h1>\n<p>A página Empresa faz parte do primeiro Projeto a ser entregue.</p>');
INSERT INTO `menu` VALUES (3,'produtos','Produtos','N','<h1>Produtos</h1>\n<p>Produzimos produtos de altíssima qualidade.</p>');
INSERT INTO `menu` VALUES (4,'servicos','Serviços','N','<h1>Serviços</h1>\n<p>Nossos serviços são referência em todo o país.</p>');
UNLOCK TABLES;
DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE `usuarios` (`id` int(11) NOT NULL AUTO_INCREMENT,`login` varchar(20) NOT NULL,`password` varchar(100) NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;
LOCK TABLES `usuarios` WRITE;
UNLOCK TABLES;